### ISSUE TITLE
[4장 질문] 303 See Other

### ISSUE THREAD

**Issue by yh20studio** [woowacourse-study/2022-http-network-basic-study#14]
@awesomeo184 

발표해주신 내용에서 303 상태코드에 대한 질문입니다.
원래 request의 http method를 get으로 바꾸어 다시 요청한다는 것이 실제로 어떤 상황에서 사용하는지 예시가 궁금합니다!

**Comment by leo0842** [comment]
흠 제가 알기로는 대충 301과 거의 비슷한데 
이전에 반환받은 Location 의 URL 값을 캐싱한 걸 쓰는지(301) 안쓰는지(303)에 대한 차이로 알고 있었는데 맞나요???
