### ISSUE TITLE
[2장 질문] Stateless VS Persistent Connection

### ISSUE THREAD

**Issue by injoon2019** [woowacourse-study/2022-http-network-basic-study#6]
HTTP는 Stateless에서 상태를 저장하지않는 않는다고 했는데, 지속 연결(Persistent Connection)에서는 연결한 히스토리를 알고 있으니 서로 상충되는게 아닌가요?

**Comment by Ohzzi** [comment]
HTTP가 상태를 저장하지 않는다는 의미는 결국 HTTP 통신이 이전에 보냈던 리퀘스트 및 리스폰스를 저장하지 않는다는 의미입니다. 연결을 유지하는 것은 상태와는 상관 없이, 그저 명시적인 연결 해제 요청이 오기 전까지는 따로 연결 해제 동작을 하지 않는다는 것을 의미합니다!
