### ISSUE TITLE
[2장 질문] Http method에서 안정성이란?

### ISSUE THREAD

**Issue by yh20studio** [woowacourse-study/2022-http-network-basic-study#8]
@Ohzzi 
설명해주신 표에서 Http Method에 대한 설명에서 안정성의 표가 있는데 이 부분에서 안전이 의미하는 것이 무엇인가요?

**Comment by Ohzzi** [comment]
보면 안전하다고 되어있는 메서드는 (목적에 맞게 설계되어 있다는 전제 하에) 서버의 상태를 변경시키지 않고 조회의 역할만 하는 데 반해, 안전하지 않다고 표시한 메서드들은 리소스를 변경시키는 동작들을 하고 있죠! 때문에 클라이언트가 리소스 변경을 시킬 수 있다는 점에서 안전하지 않다고 여기는 것입니다 :)
