### ISSUE TITLE
[2장 질문] 204 No content

### ISSUE THREAD

**Issue by yh20studio** [woowacourse-study/2022-http-network-basic-study#9]
@Ohzzi 

PUT Method를 이용했을 때 결과 값으로 200 OK 혹은 204 No Content를 사용한다고 설명해주신 점에서 질문이 있습니다.

PUT을 이용한 성공에서 204 No Content를 이용하는 이유가 있을까요? 그리고 어떤 의미를 가지고 사용하는 것인지 궁금합니다

**Comment by Ohzzi** [comment]
204 No Content는 클라이언트가 요청한 사항이 성공적으로 반영은 되었지만, 따로 서버가 바디를 담아 줄 필요가 없을 때 사용합니다. PUT 메서드가 클라이언트의 리퀘스트 바디 대로 서버 내의 리소스를 통으로 변경해주는 메서드이기 때문에, 어차피 클라이언트가 변경한 리소스 및 URI를 알고 있으므로 굳이 서버가 해당 내용을 다시 리스폰스로 내려줄 필요가 없겠죠? 때문에 204 No Content를 사용하는 것입니다!
